DROP DATABASE IF EXISTS EMPLOYEE_DB;

CREATE DATABASE EMPLOYEE_DB;

USE EMPLOYEE_DB;

CREATE TABLE DEPARTMENT (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(100),
  PRIMARY KEY (ID)
  );

CREATE TABLE ROLE (
  ID INT NOT NULL AUTO_INCREMENT,
  TITLE VARCHAR(100),
  SALARY INT,
  DEPARTMENT_ID INT NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT fk_department FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID)
);

CREATE TABLE EMPLOYEES(
  ID INT NOT NULL AUTO_INCREMENT, 
  FIRST_NAME VARCHAR(100),
  LAST_NAME VARCHAR(100),
  ROLE_ID INT NOT NULL,
  MANAGER_ID INT,
  PRIMARY KEY (ID),
  CONSTRAINT FK_role FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID),
  CONSTRAINT FK_manager FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(ID)

);

INSERT INTO DEPARTMENT (NAME)
VALUES ("manager"), ("sales"), ("warehouse"), ("accounting");

INSERT INTO ROLE (TITLE, SALARY, DEPARTMEMT_ID)
VALUES ("manager", 30000, 1), ("sales", 25000, 2), ("warehouse", 24000, 3), ("accounting", 24500, 4);

INSERT INTO EMPLOYEES (FIRST_NAME, LAST_NAME, ROLE_ID, MANAGER_ID)
VALUES ("MICHEAL", "SCOTT", 1, 0), ("PAMELA", "HALPERT", 2, 1), ("DARREL", "PHILBIN", 3, 3), ("ANGELA", "MARTIN", 4, 1);

